development:
  facebook_app_id: '1444686258898113'
  facebook_app_secret: 2af355ca211b14b997f0b9b219b15526
  google_client_id: >-
    156045701901-6hhfdv3vim2f98bmm3jro51fl3t8fkhc.apps.googleusercontent.com
  google_client_secret: 1L6CUHNd39z517sESq8W4P3p
  google_api_key: AIzaSyD_cuVyQT2E7TUQqIMCV5Jj7ocMJBhBuxI

test:
  facebook_app_id: '1444686258898113'
  facebook_app_secret: 2af355ca211b14b997f0b9b219b15526
  google_client_id: >-
    156045701901-6hhfdv3vim2f98bmm3jro51fl3t8fkhc.apps.googleusercontent.com
  google_client_secret: 1L6CUHNd39z517sESq8W4P3p
  google_api_key: AIzaSyD_cuVyQT2E7TUQqIMCV5Jj7ocMJBhBuxI

production:
  facebook_app_id: <%= ENV[FB_APP_ID] %>
  facebook_app_secret: <%= ENV[FB_APP_SECRET] %>
  google_client_id: <%= ENV["GG_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GG_CLIENT_SECRET"] %>
  google_api_key: <%= ENV["GG_API_KEY"] %>
